# Generated by Django 2.2.9 on 2019-12-22 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_1', models.CharField(help_text='word one', max_length=20)),
                ('word_2', models.CharField(help_text='word two', max_length=20)),
                ('word_3', models.CharField(help_text='word three', max_length=20)),
                ('comands', models.IntegerField()),
            ],
        ),
    ]
