# Generated by Django 3.0 on 2020-01-19 17:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time_of_adding', models.TimeField(auto_now=True)),
                ('coords', models.CharField(help_text='Coords', max_length=100)),
                ('color', models.CharField(help_text='color', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Squard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_1', models.CharField(help_text='Word 1', max_length=100)),
                ('word_2', models.CharField(help_text='Word 2', max_length=100)),
                ('word_3', models.CharField(help_text='Word 3', max_length=100)),
                ('color', models.CharField(help_text='Color', max_length=100)),
                ('time', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for comand', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='TeamName', max_length=100)),
                ('password', models.IntegerField(default=1111)),
                ('black_squard', models.ManyToManyField(blank=True, help_text='The list of Squards that belongs to this project', to='paiting_map.Squard')),
            ],
        ),
    ]
