# Generated by Django 3.0 on 2020-01-18 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paiting_map', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='squard',
            name='team',
        ),
    ]
