# Generated by Django 2.2.9 on 2019-12-22 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiting_map', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinates',
            name='comands',
            field=models.CharField(help_text='comands', max_length=20),
        ),
    ]
