# Generated by Django 2.1.7 on 2020-01-26 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paiting_map', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='squard',
            old_name='word_1',
            new_name='coord',
        ),
        migrations.RemoveField(
            model_name='delta',
            name='Time_of_adding',
        ),
        migrations.RemoveField(
            model_name='squard',
            name='time',
        ),
        migrations.RemoveField(
            model_name='squard',
            name='word_2',
        ),
        migrations.RemoveField(
            model_name='squard',
            name='word_3',
        ),
    ]
