# Generated by Django 2.2.9 on 2020-01-19 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiting_map', '0002_remove_squard_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time_of_adding', models.TimeField(auto_now=True)),
                ('coords', models.CharField(help_text='Coords', max_length=100)),
                ('color', models.CharField(help_text='color', max_length=100)),
            ],
        ),
    ]
