# Generated by Django 2.2.9 on 2019-12-23 01:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('paiting_map', '0002_auto_20191222_2011'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for comand', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='TeamName', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Scoreboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('team', models.OneToOneField(help_text='The teams', null=True, on_delete=django.db.models.deletion.SET_NULL, to='paiting_map.Comand')),
            ],
        ),
        migrations.CreateModel(
            name='Squard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_1', models.UUIDField(help_text='Word 1')),
                ('word_2', models.CharField(help_text='Word 2', max_length=100)),
                ('word_3', models.CharField(help_text='Word 3', max_length=100)),
                ('time', models.DateTimeField(auto_now=True, null=True)),
                ('team', models.OneToOneField(help_text='The team which last paint this zone', null=True, on_delete=django.db.models.deletion.SET_NULL, to='paiting_map.Comand')),
            ],
        ),
        migrations.DeleteModel(
            name='Coordinates',
        ),
        migrations.AddField(
            model_name='comand',
            name='Place',
            field=models.OneToOneField(help_text='The team place in Scoreboard', null=True, on_delete=django.db.models.deletion.SET_NULL, to='paiting_map.Scoreboard'),
        ),
        migrations.AddField(
            model_name='comand',
            name='black_squard',
            field=models.ManyToManyField(help_text='The list of Squards that belongs to this project', null=True, to='paiting_map.Squard'),
        ),
    ]
