# Generated by Django 2.2.9 on 2019-12-23 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiting_map', '0003_auto_20191223_0456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comand',
            name='black_squard',
            field=models.ManyToManyField(help_text='The list of Squards that belongs to this project', to='paiting_map.Squard'),
        ),
    ]
