# Generated by Django 2.2.9 on 2020-01-06 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiting_map', '0006_auto_20191223_0502'),
    ]

    operations = [
        migrations.AddField(
            model_name='comand',
            name='password',
            field=models.IntegerField(default=1111),
        ),
    ]
